### ISSUE TITLE
Failed at the renthouse@1.0.0 start script.

### ISSUE THREAD

**Issue by poowu** [aiyu666/rentHouse#1]
請問是否不能下載安裝renthouse@1.0.0了

**Comment by aiyu666** [comment]
嗨  
請問您的安裝錯誤有沒有相關的截圖之類的可以附上
我這邊剛剛測試是可以順利安裝執行的
![image](https://user-images.githubusercontent.com/46285572/110303761-bd26f100-8035-11eb-8a94-23c7adc2a9fb.png)

我這邊環境是 
* node 14.16.0

然後剛剛發現最後的 `npm run start` 會有問題已經解決並且推上去了
如果是這個問題的話也可以直接使用 `node app.js` 來直接執行也可以
或是麻煩幫我重新 pull master 
這邊提供一下我剛剛測試的步驟
安裝順序是
```
1. git clone git@github.com:aiyu666/rentHouse.git
2. cd ./rentHouse
3. npm install
4. 設定 README 裡面提到的相關設定
5. `npm run start` or  `node ./app.js`
```

有問題都可以再跟我說 感謝

**Comment by poowu** [comment]
我的node 也是14.16
安裝步驟已經不會出現"Failed at the renthouse@1.0.0 start script"了
而是出現"Fetch the 591 rent fail: Error: Ops! Some error about get request-> TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters"
請問README中提到的 .env = .envExample嗎?或我設定的參數格式不標準?
謝謝您

**Comment by poowu** [comment]
可以運作了  謝謝你 !

**Comment by aiyu666** [comment]
不客氣~ 記得把網頁的搜尋的條件改成時間順序這樣推播才是最新的喔 ^^
