### ISSUE TITLE
591追蹤租，有辦法改成屋主自售嗎😣

### ISSUE THREAD

**Issue by Lo-yi-chen** [aiyu666/rentHouse#2]
591 rent house check machine 
最近房子太難買..因為工作無法一直看手機，常常錯過屋主自售房屋的訊息，打過去問都是已經被付訂金帶簽約..想問一下我該怎麼更改內容😣

因為我用您的方式租屋瀏覽沒問題，但我在想是否將 rent改為sale！？

**Comment by aiyu666** [comment]
嗨您好，
我想這應該是沒問題的
剛剛我稍微觀察了一下除了 rent -> sale 外最後尾段的也要改 rsList -> list (這邊是指 591 中古屋出售那部分)
可以用一樣的方式使用唷
這是我看到的 URL 
* 中古屋
  ```
  https://sale.591.com.tw/home/search/list
  ```
* 租屋
  ```
  https://rent.591.com.tw/home/search/rsList
  ```
您可以嘗試改看看 ^^

**Comment by aiyu666** [comment]
Solved

**Comment by aiyu666** [comment]
Solved
